// MAGNIFY HELP TAB
#define MAGH1	"MAGNIFY Screen\n"
#define MAGB1	"The MAGNIFY screen displays the selected portion of the selected traces on the TRACE screen.  The data display is identical in layout definition to the TRACE Screen with the following additions:\n"
#define MAGB21	"Time Axis at top defining the length (in seconds) of the Magnify Window itself.\n"
#define MAGB22	"Time Axis at bottom defining the length of the TRACE window, with the magnified portion of the Trace highlighted (selection indicator).\n"

#define MAGH2	"SIDEBAR Functions\n"
#define MAGH3	"DISPLAY Settings\n"

#define MAGB3	"Trace Scale:\n"
#define MAGB3A	"Define the Y-Axis maximum and minimum values of each individual trace\n"
#define MAGB30  "Fixed\n"
#define MAGB301 "Use the User-supplied values for Max and Min\n"
#define MAGB30A "max:\n"
#define MAGB30A1 "Specified as a fixed value (e.g., 1000), or as a Percentage of Max/Min Mean (e.g., 50%).  Leave blank to use actual real Maximum\n"
#define MAGB30B "min:\n"
#define MAGB30B1 "Specified as a fixed value (e.g., 1000), or as a Percentage of Max/Min Mean (e.g., 50%).  Leave blank to use actual real Minimum\n"
#define MAGB31	"On Display\n"
#define MAGB311	"Use max and min values of the selected portion on display\n"
#define MAGB32	"Whole Trace:\n"
#define MAGB321	"Use max and min values of the entire trace\n"

#define MAGB4	"Window Scale:\n"
#define MAGB4A	"Define the Amplitude Axis max and min values of each individual trace\n"
#define MAGB41	"Trace\n"
#define MAGB411	"Use max and min values of the Trace itself\n"
#define MAGB42	"Window:\n"
#define MAGB421	"Use max and min values of all Traces currently displayed\n"

#define MAGB5	"Display as:\n"
#define MAGB5A	"COUNTS or VOLTS, see TRACE Help for details\n"

#define MAGB6	"Overlay:\n"
#define MAGB6A	"Turn Overlay mode ON and OFF, Overlay colors defined in Controls Panel\n"

#define MAGB7	"Filter:\n"
#define MAGB7A	"Turn Filter ON and OFF, Filter settings defined in Controls Panel, (See CONTROLS Help for more info)\n"

#define MAGH4	"MAGNIFY Buttons\n"
#define MAGB8	"SNAP\n"
#define MAGB8A	"Move (single) vertical line to SNAP-TO point\n"
#define MAGB81	"MAGNIFY\n"
#define MAGB81A	"Re-Display MAGNIFY screen using (double) vertical lines as magnify boundaries\n"
#define MAGB81B	"(MAGNIFY button displayed in place of SNAP button when two vertical lines defined)\n"
#define MAGB9	"Zoom Anchor:\n"
#define MAGB9A	"Define anchor point for ZOOM and SNAP actions to be one of:\n"
#define MAGB91	"LEFT"
#define MAGB911	"\tedge of Magnify Screen\n"
#define MAGB92	"MIDDLE"
#define MAGB921	"\tof Magnify Screen\n"
#define MAGB93	"RIGHT"
#define MAGB931	"\tedge of Magnify Screen\n"

#define MAGB10	"Picking:\n"
#define MAGB10A	"Define scope of Pick actions to be one of:\n"
#define MAGB10B	"Trace"
#define MAGB10B1	"\tPicks are defined for a specific Trace only\n"
#define MAGB10C	"Window"
#define MAGB10C1	"\tPicks are defined for all Traces currently Magnified\n"
#define MAGB11	"Write Picks\n"
#define MAGB11A	"Write currently defined Picks to Pick File.  See MOUSE FUNCTIONS and CONTROL OPTIONS below for complete details.\n"

#define MAGH5	"MOUSE Functions\n"
#define MAGB12	"Moving The Window\n"
#define MAGB121	"Zooming IN and OUT\n"
#define MAGB1211 "CLICK+DRAG RIGHT to ZOOM IN\n"
#define MAGB1212 "CLICK+DRAG LEFT to ZOOM OUT\n"
#define MAGB122	"SNAP to Point\n"
#define MAGB1221 "Within the plot region, CLICK (to make vertical line) to define SNAP-TO point, followed by SNAP Button on Sidebar.\n"
#define MAGB123	"JUMP SCROLL\n"
#define MAGB1231 "LEFT"
#define MAGB12311 "\tWithin bottom time axis, CLICK to the LEFT of the selection indicator\n" 
#define MAGB1232 "RIGHT"
#define MAGB12321 "\tWithin bottom time axis, CLICK to the RIGHT of the selection indicator\n" 
#define MAGB124	"SCROLL\n"
#define MAGB1241 "Within bottom time axis, CLICK on Selection Indicator, and DRAG right or left\n"
#define MAGB125 "JUMP to Point\n"
#define MAGB1251 "Within bottom time axis, SHIFT+CLICK at desired SNAP-TO point\n"
#define MAGB126 "Display Data Point Values and Deltas - Time and Amplitude\n"
#define MAGB1261 "CTRL+CLICK within desired trace, information is displayed in status bar at bottom.\nSelect a 2nd data point to see the differences with the 1st point, works across multiple traces.\n"
#define MAGB127 "Scan Data Point Values - Time and Amplitude\n"
#define MAGB1271 "CTRL+CLICK+DRAG within desired trace\n"

#define MAGB128	"PICKING\n"
#define MAGB1281 "PQL II now provides enahanced picking abilities.  Up to 10 different Pick specifiers can be defined (via Controls Panel, see below).  Indicating a Pick for writing is as follows:\n"
#define MAGB1281A "Normal PICK\n"
#define MAGB1282 "Use the number keys 0-9 (0 = Pick 10) to identify which Pick is being defined, followed by SHIFT+CLICK at the desired Pick point.\n"
#define MAGB1281B "Error PICK\n"
#define MAGB12821 "Use the number keys 0-9 (0 = Pick 10) to identify which error Pick is being defined, followed by SHIFT+ALT+CLICK at the desired error Pick point.  (Pick name will have an 'e' pre-pended to defined Pick specifier.)\n"
#define MAGB1283 "Additionally, when writing the Pick File, KEYWORDS and/or a COMMENTARY may also be provided.  If either are turned ON (via CONTROLS panel), when writing the Pick file, a dialogue will be presented allowing for the Pick File Name to be specified (if undefined via CONTROLS panel), and (optional) KEYWORDS and a COMMENTARY to be provided.\n"
#define MAGB1284 "KEYWORDS are useful if, at a later time, one or more Pick Files are queried (e.g., by grep) for locating similar Pick types across multiple writes of Picks.  In this manner, pre-defined KEYWORDS may be created relevant to a particular dataset that can later be queried on for analysis.\n"
#define MAGB1285 "COMMENTARY is useful for adding free format text for a particular Pick.  As well, the COMMENTARY is written at the bottom left corner of the plot region; useful if wanting to PRINT the screen with the PICK information.\n"
#define MAGB1286 "Reading Pick Files for re-display is not supported at this time, however, picks which have been written to a Pick File for a trace are re-plotted as long as the trace is still currently 'read-in'.\n"

#define MAGB13	"Bring Trace to TOP\n"
#define MAGB13A "In OVERLAY mode, Traces may be obscured by other traces plotted on top.  To re-plot a Trace on top, CLICK on the Trace label.  Defining this, then, to be the current 'Top Trace' also specifies that Data Point Display functionality will also act on this Trace.  Default 'Top Trace' is the last Trace on display.\n" 

#define MAGH6 "CONTROL Screen Options\n"
#define MAGB14 "Zoom/Scrolling Factors:\n"
#define MAGB141 "Zoom\n"
#define MAGB1411 "Define the Zoom Speed, higher is faster, valid values from 10 - 200.  (N.B: There is a relationship here with the CPU speed, slower CPU's will benefit from a higher value, while faster CPU's will work better with a lower value.)\n"
#define MAGB142 "Scrolling\n"
#define MAGB1421 "Define the Jump Scroll Distance, as a percentage of selection on display, valid values from 5 - 95.\n"
#define MAGB15 "Picking:\n"
#define MAGB151 "Pick Filename\n"
#define MAGB1511 "Define the name of the Pick File for writing.\n"
#define MAGB152 "Write Options:\n"
#define MAGB1521 "KEYWORDS\n"
#define MAGB15211 "Specify whether KEYWORDS should be provided when writing the Pick File.\n"
#define MAGB1522 "COMMENTARY\n"
#define MAGB15221 "Specify whether a COMMENTARY should be provided when writing the Pick File.\n"
#define MAGB153 "Tag Names:\n"
#define MAGB1531 "Define the tag names which are to be used when Picking.  Up to 10 distinct Picks may be defined, maximum 10 characters each.\n"
#define MAGB16	"Indicator Flags:\n"
#define MAGB161	"Turn ON and OFF Gap and Overlap flags.  See TRACE Help for more info on Gaps and Overlaps.\n"
#define MAGB17	"SideBar Display:\n"
#define MAGB17A	"On some computer display screens, the MAGNIFY screen is vertically too large to display fully.  These settings allow for the Zoom Anchor and Picking Scope specifications to be hidden, thus making the MAGNIFY screen small enough for full display.\n"
#define MAGB18 "Colors\n"
#define MAGB181 "Define the various settable colors for the screen\n"
#define MAGB19 "Buttons\n"
#define MAGB191 "Continue\n"
#define MAGB1911 "Apply new settings and return to the MAGNIFY screen\n"

